### ISSUE TITLE
Does the REST API doesn't work for Test Enviroment?

### ISSUE THREAD

**Issue by dvriv** [tuxxx128/G2A-PAY-PHP5-API#1]
Is not working for me, even after changing the variable for REST_TEST_URL. I am getting NULL, not sure if I am doing something wrong or the Rest API doesn't work for Test. Any idea? Thank you

**Comment by dvriv** [comment]
Got it, It needs to have www like this: https://www.test.pay.g2a.com/rest

**Comment by tuxxx128** [comment]
www? no?!

So, it works? I had same problem, but i thought that test version doesn't completely implementation..for me still doesn't work: detail of order and if i don't approved G2A PAY test account - nothing works :-)

I tested sometimes on production..

**Comment by dvriv** [comment]
Yeah It worked for me using the URL with www.
Well I am only using getPaymentDetailById not sure if the other REST functions works but that is working.

**Comment by tuxxx128** [comment]
OK, you are right, i now find this: https://pay.g2a.com/documentation/dev-environments
