### ISSUE TITLE
Hash calculation issue

### ISSUE THREAD

**Issue by ChrisBPB** [tuxxx128/G2A-PAY-PHP5-API#2]
It could be a good idea to add the following during the hash calculation. 
`(number_format($amount, 2)+0)`

Because, as shown in the api docs 
2.22 = 2.22
2.20 = 2.2
2.00 = 2

if you calculate the hash with trailing 0's it will be incorrect. You can get around this by formatting the number prior to passing it to the calculate function but it seems more pleasant this way.

It caused me issues as at the time it wasn't in the docs that trailing 0's had to be removed, once I worked it out I told them about it and they have since added it to the docs.

**Comment by tuxxx128** [comment]
Sorry i'm late, but is still current? I looked to API DOCS and now i don't see notice of this issue, maybe developers did any changes, otherwise can you send me link to API DOCS, where is it?..

**Comment by ChrisBPB** [comment]
https://pay.g2a.com/documentation/payment-notifications#amount-example

**Comment by tuxxx128** [comment]
Thanks, you are right, it's good idea `(number_format($amount, 2)+0)` i will fix it :+1:
