### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by Dieterfu** [tuxxx128/G2A-PAY-PHP5-API#3]
Hello,
 do you have a Version of G2A-PAY-PHP5-API  which I can use without Composer?

Thank you very much
With best regards
Dieter

**Comment by tuxxx128** [comment]
Hi, i don't have, if you have experience with PHP, you can download files from Github as .ZIP file and include files from 'src' folder to your project, other files are not required..

Next step is load all files from 'src' folder in your script file (example require_once)...

**Comment by Dieterfu** [comment]
ok, Thank you very much.
I add all files with require_once to my Project files, but now I get the error message: Fatal error: Interface 'Tuxxx128\G2aPay\IG2aPay' not found in /var/www/html/examples/src/G2aPay/G2aPayApi.php on line 11

with best Regards
Dieter

**Comment by tuxxx128** [comment]
also you add to require_once IG2aPay.php? Please show me the file..

**Comment by Dieterfu** [comment]
`<?php

require_once 'src/G2aPay/G2aPayApi.php';
require_once 'src/G2aPay/G2aPayException.php';
require_once 'src/G2aPay/G2aPayItem.php';
require_once 'src/G2aPay/IG2aPay.php';

$g2aPayApi = new G2aPayApi('API HASH', 'SECRET KEY', false, 'store.email@server.tld'); // test environment

// Order items

// item - 1
$itemOne = (new G2aPayItem)->itemTemplate();

$itemOne->name = "My item #1";
$itemOne->url = "http://google.com";
$itemOne->price = 10; // default currency is 'EUR'

$g2aPayApi->addItem($itemOne);

// item - 2
$itemTwo = (new G2aPayItem)->itemTemplate();

$itemTwo->name = "My item #2";
$itemTwo->url = "http://google.com";
$itemTwo->price = 20; // default currency is 'EUR'

$g2aPayApi->addItem($itemTwo);

// Discount item
$itemDiscount = (new G2aPayItem)->itemTemplate();

$itemDiscount->name = "Discount";
$itemDiscount->url = "http://google.com";

$g2aPayApi->addPercentDiscountItem($itemDiscount, 25);

// Set required parameters and redirect to payment gateway

$g2aPayApi->setUrlFail("https://www.google.cz/?gfe_rd=cr&ei=98-bWN6ZDbGE8QfwhpnQCw&gws_rd=ssl#q=bad");
$g2aPayApi->setUrlSuccess("https://www.google.cz/?gfe_rd=cr&ei=98-bWN6ZDbGE8QfwhpnQCw&gws_rd=ssl#q=success");
$g2aPayApi->setOrderId(1234);
// $g2aPayApi->setEmail('user@server.tld');

header('Location: '.$g2aPayApi->getRedirectUrlOnGateway());
die;`

**Comment by tuxxx128** [comment]
Try change order of the files..

require_once 'src/G2aPay/G2aPayException.php';
require_once 'src/G2aPay/IG2aPay.php';
require_once 'src/G2aPay/G2aPayApi.php';
require_once 'src/G2aPay/G2aPayItem.php';

**Comment by Dieterfu** [comment]
Thank you.
Now it Shows that error message: Fatal error: Class 'G2aPayApi' not found in /var/www/html/examples/fullProcess.php on line 9

Line 9: $g2aPayApi = new G2aPayApi('API HASH', 'SECRET KEY', false, 'store.email@server.tld'); // test environment

**Comment by tuxxx128** [comment]
NS!

Try:

```
<?php

use Tuxxx128\G2aPay\G2aPayItem;
use Tuxxx128\G2aPay\G2aPayApi;
```

**Comment by Dieterfu** [comment]
thank you.
Should I paste it after require_one or before?

**Comment by tuxxx128** [comment]
before
