### ISSUE TITLE
Question: Invalid Store

### ISSUE THREAD

**Issue by Hodel1** [tuxxx128/G2A-PAY-PHP5-API#4]
Hi,

i have a problem. I use this library and debugged it, because there is a wrong parameter.
So i get the Message: "Invalid Store".

Can you tell me where is my error?
I have a question, what is the definition of order_id? Is this my personally orderId in my Shopsystem or is it anything from g2a internals?

i have debugged so much, but i can't find the error :/

My Code:

            if (env('G2APAY_API_ENV') == "test") {
                $g2aPayApi = new G2aPayApi(env('G2APAY_API_HASH'), env('G2APAY_API_SECRET'), false, env('G2APAY_API_EMAIL'));
            } else {
                $g2aPayApi = new G2aPayApi(env('G2APAY_API_HASH'), env('G2APAY_API_SECRET'), true, env('G2APAY_API_EMAIL'));
            }
            
            $item = (new G2aPayItem)->itemTemplate();
            $item->name = $product->productname;
            $item->url = url("/products");
            $item->price = (float)$product->productprice;
            $item->id = $product->id;
            
            $g2aPayApi->addItem($item);
            
            $g2aPayApi->setUrlFail(url('/purchase/payment/cancel'));
            $g2aPayApi->setUrlSuccess(url('/purchase/payment/' . $playerpurchase->id . '/' . $customhash));

            $g2aPayApi->setOrderId($playerpurchase->id);

            Redirect::to($g2aPayApi->getRedirectUrlOnGateway());

**Comment by tuxxx128** [comment]
Hi 

"Invalid Store" - sounds like bad email of store..
Order ID - is unique string for your new order, you can generate own, but must be unique or use from your system if is generating unique ID..

What do you testing production or dev mode?

**Comment by Hodel1** [comment]
Hey, thanks for your fast reply :)
Im developing on Win10, with Laravel 5 and use internal php(from xampp, php5) server (php artisan serv)

I tried this Code below in dev and production mode. Both is failed.

The email of store is not needed in this request, because $g2aPayApi->getRedirectUrlOnGateway() returns G2aPayApi::buildHttpRequest() - there is no Email needed, only Apihash and hash ({userOrderId}{amount}{currency}{ApiSecret}) 

greets

**Comment by tuxxx128** [comment]
Redirect link is returned, but you need set email of you store before redirecting, because your APP keys can has more gateways..

**Comment by Hodel1** [comment]
i think we had found the issue. the store was not verified :D

**Comment by tuxxx128** [comment]
yes, i'ts one option, i have question on you, test environment is works after register test account without vertification or no?

**Comment by Hodel1** [comment]
I registered an account on test.pay.g2a.com and used this apidata. (Without verification etc.) and get the same response:

{#271 ▼
  +"status": false
  +"error": true
  +"message": "Invalid store"
  +"title": null
  +"code": "MVI0002"
  +"params": []
  +"details": null
  +"__token__": "e3c456ffd0ffdd0db8dd205cfd57500b"
  +"__token_key__": "6KDaSbcgdcod5k4W"
}
