### ISSUE TITLE
Can't know which error is given by G2A Pay

### ISSUE THREAD

**Issue by necipallef** [tuxxx128/G2A-PAY-PHP5-API#5]
I get G2aPayException with the message 'Something is wrong, returned token is invalid, please check your sent parameters', but this is not enough. I need to see the details. G2A Pay API gives the details but there is no way to get them using this library yet.

**Comment by tuxxx128** [comment]
Yes, some details G2A PAY is returned, i added more info about exception (https://github.com/tuxxx128/G2A-PAY-PHP5-API/blob/master/src/Tuxxx128/G2aPay/G2aPayApi.php#L213), you can update the lib..

_composer require "tuxxx128/g2a-pay-php5-api":"dev-master"_

**Comment by necipallef** [comment]
Thanks for the quick fix. But sometimes 'details' returns null by the G2A API and only 'message' is given. You could add 'message' field as well.

**Comment by necipallef** [comment]
My quick solution was this
`$result = var_export($result, true);
            throw new G2aPayException('Something is wrong, returned token is invalid, please check your sent parameters. ' . $result);`

**Comment by tuxxx128** [comment]
Complete result is better solution, thanks: composer require "tuxxx128/g2a-pay-php5-api":"v1.2.1"
