### ISSUE TITLE
I have a problem whith token

### ISSUE THREAD

**Issue by vaduk1390** [tuxxx128/G2A-PAY-PHP5-API#6]
I hooked it all on Wordpess and got an error:
Fatal error: Uncaught exception 'Tuxxx128\G2aPay\G2aPayException' with message 'Something is wrong, returned token is invalid, please check your sent parameters.  All parrametrs in g2a is correct. Please inquire about the solution

**Comment by tuxxx128** [comment]
Please update the library, because new version has more info about exception..
