### ISSUE TITLE
My G2A IPN is not working?

### ISSUE THREAD

**Issue by Galliger** [tuxxx128/G2A-PAY-PHP5-API#8]
DELETED

**Comment by Galliger** [comment]
I have tested all my statements by posting test data, it must be failing when calculating the IPN hash?

What have I done wrong?

**Comment by Galliger** [comment]
I have put the IPN url in the website URL box but it doesn't seem to be posting the data to the link and updating the database?

**Comment by tuxxx128** [comment]
I readed this :-) next time you can check it if IPN is working..save arrival POST data...

`<?php

$log = fopen('log.txt', 'a+');
fwrite($log, serialize($_POST));
fclose($log);`
